version: '3'
services:
  discollama:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ['--redis-host', 'redis']
    environment:
      - DISCORD_TOKEN=
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama3.1:70b
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - discollama-net
    depends_on:
      - ollama
      - redis

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - discollama-net

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - /home/austin/disk2/ollama_data:/root/.ollama
    ports:
      - "11435:11434"
    networks:
      - discollama-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  discollama-net:
    driver: bridge